name: Deploy Gloamin

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Zola
        uses: taiki-e/install-action@v2
        with:
          tool: zola

      - name: Build site
        run: zola build

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/github_actions_deploy
          chmod 600 ~/.ssh/github_actions_deploy

          echo "${{ secrets.KNOWN_HOSTS }}" > ~/.ssh/known_hosts

      - name: Deploy to VPS
        run: |
          rsync -avz --delete \
            -e "ssh -i ~/.ssh/github_actions_deploy -p ${{ secrets.PORT }}" \
            public/ \
            ${{ secrets.USERNAME }}@${{ secrets.HOST }}:/var/www/gloamin/public/
